#!/usr/bin/env tsx
/**
 * Hanuja New Client Generator
 *
 * Usage:
 *   pnpm new-client
 *   pnpm new-client --name="Moda Evi" --primary="#2d1b69" --accent="#ff6b35"
 *
 * What it does:
 *   1. Prompts for client name (or reads --name flag)
 *   2. Asks for primary color, accent color (or uses safe defaults)
 *   3. Generates packages/config/brand/{slug}.brand.ts
 *   4. Generates a summary of next steps
 *
 * After running:
 *   - Update .env with client domain, credentials, bucket
 *   - Update apps/*/src/app/globals.css :root values to match new brand
 *   - Replace logo/favicon assets
 *   - Run `pnpm db:migrate && pnpm db:seed`
 *   - Deploy via Coolify
 */

import fs from 'node:fs'
import path from 'node:path'
import readline from 'node:readline'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '../../')

// ─── Helpers ────────────────────────────────────────────────────────────────

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/ş/g, 's')
    .replace(/ğ/g, 'g')
    .replace(/ü/g, 'u')
    .replace(/ö/g, 'o')
    .replace(/ı/g, 'i')
    .replace(/ç/g, 'c')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function parseArgs(): Record<string, string> {
  const args: Record<string, string> = {}
  for (const arg of process.argv.slice(2)) {
    const match = arg.match(/^--(\w[\w-]*)(?:=(.*))?$/)
    if (match) {
      args[match[1] ?? ''] = match[2] ?? 'true'
    }
  }
  return args
}

async function prompt(question: string, fallback?: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
  return new Promise((resolve) => {
    const suffix = fallback ? ` (default: ${fallback}): ` : ': '
    rl.question(question + suffix, (answer) => {
      rl.close()
      resolve(answer.trim() || fallback || '')
    })
  })
}

// ─── Brand file template ────────────────────────────────────────────────────

function generateBrandFile(opts: {
  name: string
  slug: string
  primary: string
  primaryFg: string
  accent: string
  accentFg: string
  fontSans: string
  fontDisplay: string
}): string {
  return `import type { BrandConfig } from './brand.config'

/**
 * ${opts.name} brand configuration.
 * Generated by tools/generators/new-client.ts
 *
 * Next steps:
 * 1. Update color values to match client brand guidelines
 * 2. Copy :root block to apps/*/src/app/globals.css
 * 3. Update font imports in layout.tsx if using custom fonts
 */
export const ${opts.slug.replace(/-([a-z])/g, (_, c: string) => (c as string).toUpperCase())}Brand: BrandConfig = {
  name: '${opts.name}',
  slug: '${opts.slug}',

  colors: {
    primary: '${opts.primary}',
    primaryFg: '${opts.primaryFg}',

    secondary: '#16213e',
    secondaryFg: '#ffffff',

    accent: '${opts.accent}',
    accentFg: '${opts.accentFg}',

    surface: '#ffffff',
    background: '#fafafa',

    border: '#e5e7eb',

    muted: '#f3f4f6',
    mutedFg: '#6b7280',

    destructive: '#ef4444',
    destructiveFg: '#ffffff',

    success: '#22c55e',
    warning: '#f59e0b',
  },

  typography: {
    fontSans: '${opts.fontSans}',
    fontDisplay: '${opts.fontDisplay}',
    fontMono: "'JetBrains Mono', 'Fira Code', monospace",
  },

  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    full: '9999px',
  },
}
`
}

function generateRootCss(opts: {
  name: string
  slug: string
  primary: string
  primaryFg: string
  accent: string
  fontSans: string
  fontDisplay: string
}): string {
  return `/*
 * ${opts.name} Brand Design Tokens
 * Generated from packages/config/brand/${opts.slug}.brand.ts
 * Copy this :root block into your apps/*/src/app/globals.css
 */
:root {
  --color-primary: ${opts.primary};
  --color-primary-fg: ${opts.primaryFg};
  --color-secondary: #16213e;
  --color-secondary-fg: #ffffff;
  --color-accent: ${opts.accent};
  --color-accent-fg: #ffffff;
  --color-surface: #ffffff;
  --color-background: #fafafa;
  --color-border: #e5e7eb;
  --color-muted: #f3f4f6;
  --color-muted-fg: #6b7280;
  --color-destructive: #ef4444;
  --color-destructive-fg: #ffffff;
  --color-success: #22c55e;
  --color-warning: #f59e0b;

  --font-sans: ${opts.fontSans};
  --font-display: ${opts.fontDisplay};
  --font-mono: 'JetBrains Mono', 'Fira Code', monospace;

  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --radius-xl: 16px;
  --radius-full: 9999px;
}`
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n🏪  Hanuja — New Client Generator\n')
  console.log('This will create a brand config file for a new client marketplace.\n')

  const args = parseArgs()

  const name = args['name'] ?? (await prompt('Client marketplace name', 'Yeni Marketplace'))
  const slug = slugify(name)
  const primary = args['primary'] ?? (await prompt('Primary color (hex)', '#1a1a2e'))
  const primaryFg = args['primaryFg'] ?? (await prompt('Primary foreground color (hex)', '#ffffff'))
  const accent = args['accent'] ?? (await prompt('Accent color (hex)', '#e94560'))
  const accentFg = args['accentFg'] ?? '#ffffff'
  const fontSans =
    args['fontSans'] ?? (await prompt("Body font (Google Fonts name)", "'Inter', system-ui, sans-serif"))
  const fontDisplay =
    args['fontDisplay'] ??
    (await prompt('Display/heading font', "'Playfair Display', Georgia, serif"))

  const brandDir = path.join(repoRoot, 'packages/config/brand')
  const brandFile = path.join(brandDir, `${slug}.brand.ts`)
  const cssSnippetFile = path.join(brandDir, `${slug}.root.css`)

  // Write brand file
  const brandContent = generateBrandFile({
    name,
    slug,
    primary,
    primaryFg,
    accent,
    accentFg,
    fontSans,
    fontDisplay,
  })
  fs.writeFileSync(brandFile, brandContent, 'utf-8')

  // Write CSS snippet
  const cssContent = generateRootCss({ name, slug, primary, primaryFg, accent, fontSans, fontDisplay })
  fs.writeFileSync(cssSnippetFile, cssContent, 'utf-8')

  console.log('\n✅  Generated files:')
  console.log(`   ${path.relative(repoRoot, brandFile)}`)
  console.log(`   ${path.relative(repoRoot, cssSnippetFile)}`)
  console.log('\n📋  Next steps:')
  console.log(`   1. Review packages/config/brand/${slug}.brand.ts — adjust colors/fonts`)
  console.log(`   2. Copy ${slug}.root.css :root block → apps/*/src/app/globals.css`)
  console.log(`   3. Update .env → domain, Iyzico credentials, R2 bucket, Meilisearch`)
  console.log('   4. Replace apps/web/public/logo.* and favicon.ico')
  console.log('   5. Run: pnpm db:migrate && pnpm db:seed')
  console.log('   6. Deploy via Coolify\n')
}

main().catch((err) => {
  console.error('Generator failed:', err)
  process.exit(1)
})
